# Generated by Django 3.0.8 on 2020-08-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200803_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='startBiding',
        ),
    ]
