# Generated by Django 3.0.8 on 2020-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
