# Generated by Django 3.0.8 on 2020-08-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest_bid',
            field=models.IntegerField(blank=True),
        ),
    ]
